In [4]:
import os
import pandas as pd
from subprocess import call, check_output

## pheno example

In [240]:
data

    sample  y
0  sample0  0
1  sample1  1
2  sample2  0
3  sample3  0
4  sample4  1
5  sample5  0
6  sample6  0
7  sample7  0
8  sample8  0

In [ ]:
gwas_file_name = "GWAS_File_Name"
pheno = data

## PLINK Class

In [244]:
class PLINK: 
    def __init__(self):
        
        print("Hello PLINK")
        
    def assoc(self, gwas_file_name, pheno , allow_no_sex = True ,output_name="result"):
        fid = pd.DataFrame(pheno.iloc[:,0])
        new_pheno = pd.concat([fid,pheno],1)
        
        if (allow_no_sex) == True:
            allow_no_sex = "--allow-no-sex"
        
        else:
            allow_no_sex = None
            
        
        if sum(new_pheno.columns == ['FID','IID','Y']) == 3:
            
            new_pheno.loc[(new_pheno['Y']==1),"Y"]=2
            new_pheno.loc[(new_pheno['Y']==0),"Y"]=1
                
            
            new_pheno.to_csv("phenotype",index=False,sep=" ")
            
            call(["plink", "--bfile", gwas_file_name, "--assoc", "--pheno", "phenotype", allow-no-sex, "--geno", "0.00001", "--out", output_name])
        else:
            new_pheno.columns = ['FID','IID','Y']
            
            new_pheno.loc[(new_pheno['Y']==1),"Y"]=2
            new_pheno.loc[(new_pheno['Y']==0),"Y"]=1
            
            new_pheno.to_csv("phenotype",index=False,sep=" ")
            
            call(["plink", "--bfile", gwas_file_name, "--assoc", "--pheno", "phenotype", allow-no-sex, "--geno", "0.00001", "--out", output_name])
        
        result = pd.read_table(f"{output_name}.assoc",delimiter=r"\s+")
        
        return result   
    
    
    
    
    def qassoc(self, gwas_file_name, pheno , allow_no_sex = True,output_name="result"):
        fid = pd.DataFrame(pheno.iloc[:,0])
        new_pheno = pd.concat([fid,pheno],1)
        
        if sum(new_pheno.columns == ['FID','IID','Y']) == 3:
        
                
            
            new_pheno.to_csv("phenotype",index=False,sep=" ")
            
            call(["plink", "--bfile", gwas_file_name, "--linear", "--pheno", "--all-pheno", "phenotype", allow-no-sex, "--geno", "0.00001", "--out", output_name])
        else:
            new_pheno.columns = ['FID','IID','Y']
            
            
            new_pheno.to_csv("phenotype",index=False,sep=" ")
            
            call(["plink", "--bfile", gwas_file_name, "--linear", "--pheno", "--all-pheno", "phenotype", allow-no-sex, "--geno", "0.00001", "--out", output_name])
        
        result = pd.read_table(f"{output_name}.qassoc",delimiter=r"\s+")
        
        return result  
    
    
    
    
    def model(self, gwas_file_name, pheno, allow_no_sex = True, output_name="result"):
        
        fid = pd.DataFrame(pheno.iloc[:,0])
        new_pheno = pd.concat([fid,pheno],1)
        
        if sum(new_pheno.columns == ['FID','IID','Y']) == 3:
            
                
            new_pheno.loc[(new_pheno['Y']==1),"Y"]=2
            new_pheno.loc[(new_pheno['Y']==0),"Y"]=1
                
            
            new_pheno.to_csv("phenotype",index=False,sep=" ")
            
            call(["plink", "--bfile", gwas_file_name, "--model", "--pheno", "phenotype", allow-no-sex, "--geno", "0.00001", "--out", output_name])
        else:
            new_pheno.columns = ['FID','IID','Y']
            
            new_pheno.loc[(new_pheno['Y']==1),"Y"]=2
            new_pheno.loc[(new_pheno['Y']==0),"Y"]=1
            
            new_pheno.to_csv("phenotype",index=False,sep=" ")
            
            call(["plink", "--bfile", gwas_file_name, "--model", "--pheno", "phenotype", allow-no-sex, "--geno", "0.00001", "--out", output_name])
        
        result = pd.read_table(f"{output_name}.model",delimiter=r"\s+")
        
        return result
    
    
    
    def clump(self, gwas_file_name, clump_file_name, output_name = "result"):
        
        ## ex) clump_file_name format is "clump_file_name.assoc"

        call(["plink", "--bfile", gwas_file_name, "--clump", clump_file_name, allow-no-sex, "--out", output_name])
        
        result = pd.read_table(f"{output_name}.clumped",delimiter=r"\s+")
        return result
    
    #def to_matrix()

## PLINK build

In [245]:
p = PLINK()

Hello PLINK

In [230]:
assoc = p.assoc(gwas_file_name,y_train.iloc[:,1:3],allow_no_sex=True,output_name=output_name)

/data/jang/jang/tool/anaconda3/envs/ML/lib/python3.7/site-packages/ipykernel_launcher.py:32: FutureWarning: read_table is deprecated, use read_csv instead.

In [231]:
assoc.sort_values("P")

,CHR,SNP,BP,A1,F_A,F_U,A2,CHISQ,P,OR
36337,12,rs117820043,108430399,G,0.11840,0.012770,A,27.330000,1.712000e-07,10.3900
24135,7,rs144593206,152549826,A,0.09211,0.006383,G,26.740000,2.330000e-07,15.7900
13842,4,rs188516474,134664591,G,0.06579,0.002128,A,24.400000,7.843000e-07,33.0300
48810,20,rs6038805,7381009,C,0.09211,0.008511,T,23.160000,1.492000e-06,11.8200
42462,16,rs192151622,21709954,T,0.07895,0.006383,C,21.250000,4.034000e-06,13.3400
12436,4,rs139454297,31136663,G,0.07895,0.006383,T,21.250000,4.034000e-06,13.3400
50747,22,rs9605004,19668110,G,0.21050,0.057450,A,21.130000,4.291000e-06,4.3750
39609,14,rs118125172,84374552,C,0.09211,0.010640,T,20.200000,6.976000e-06,9.4350
40974,15,rs150231433,65349897,C,0.06579,0.004255,T,19.570000,9.685000e-06,16.4800
43779,16,rs188481973,87668108,T,0.06579,0.004255,C,19.570000,9.685000e-06,16.4800
48811,20,rs6117805,7419920,T,0.06579,0.004255,C,19.570000,9.685000e-06,16.4800
35929,12,rs75532401,83402125,G,0.06579,0.004255,C,19.570000,9.685000e-06,16.4800
41559,15,rs89062,93216244,A,0.07895,0.008511,G,18.050000,2.149000e-05,9.9860
16088,5,rs138423132,78085903,G,0.07895,0.008511,A,18.050000,2.149000e-05,9.9860
32950,11,rs78791032,45939848,C,0.07895,0.008511,A,18.050000,2.149000e-05,9.9860
1706,1,rs754001,87379986,C,0.07895,0.008511,T,18.050000,2.149000e-05,9.9860
37879,13,rs150582084,81511085,T,0.09211,0.012770,C,17.720000,2.562000e-05,7.8450
39098,14,rs7158191,59301948,A,0.13160,0.027660,G,17.510000,2.859000e-05,5.3260
26418,8,rs17292295,108186012,A,0.15790,0.040430,G,16.860000,4.030000e-05,4.4510
10420,3,rs115814039,126841894,T,0.11840,0.023400,C,16.740000,4.293000e-05,5.6050
40365,15,rs7180788,34182089,G,0.06579,0.006383,A,15.990000,6.361000e-05,10.9600
16613,5,rs144720593,119753890,C,0.06579,0.006383,A,15.990000,6.361000e-05,10.9600
13528,4,rs148847534,110154152,A,0.06579,0.006383,G,15.990000,6.361000e-05,10.9600
31441,10,rs143273589,110215556,A,0.06579,0.006383,G,15.990000,6.361000e-05,10.9600
10988,3,rs189607229,160487063,T,0.06579,0.006383,G,15.990000,6.361000e-05,10.9600
35928,12,rs3993374,83358353,T,0.34210,0.153200,G,15.850000,6.844000e-05,2.8740
50608,21,rs9974185,45797916,A,0.09211,0.014890,G,15.610000,7.780000e-05,6.7100
28960,9,rs117312059,117832291,T,0.09211,0.014890,C,15.610000,7.780000e-05,6.7100
20421,6,rs146337832,125872872,A,0.07895,0.010640,G,15.460000,8.410000e-05,7.9710
11838,4,rs10937705,6183184,T,0.07895,0.010640,G,15.460000,8.410000e-05,7.9710
...,...,...,...,...,...,...,...,...,...,...
39261,14,rs7158088,67116995,G,0.42110,0.421300,A,0.000013,9.971000e-01,0.9991
17504,5,rs8180418,170042369,T,0.43420,0.434000,C,0.000008,9.978000e-01,1.0010
25294,8,rs13255179,31192810,T,0.43420,0.434000,C,0.000008,9.978000e-01,1.0010
38997,14,rs4901375,53714056,G,0.43420,0.434000,A,0.000008,9.978000e-01,1.0010
27696,9,rs10757213,21317899,G,0.43420,0.434000,C,0.000008,9.978000e-01,1.0010
5714,2,rs6547155,77786742,G,0.21050,0.210600,A,0.000005,9.982000e-01,0.9993
49955,21,rs2823103,16529439,C,0.21050,0.210600,T,0.000005,9.982000e-01,0.9993
19480,6,rs1328991,47877826,G,0.21050,0.210600,A,0.000005,9.982000e-01,0.9993
12270,4,rs7675704,23332100,C,0.21050,0.210600,G,0.000005,9.982000e-01,0.9993
14396,4,rs10029237,168098935,G,0.21050,0.210600,A,0.000005,9.982000e-01,0.9993
42079,16,rs12921822,7052774,C,0.21050,0.210600,T,0.000005,9.982000e-01,0.9993
46479,18,rs4939883,47167214,T,0.21050,0.210600,C,0.000005,9.982000e-01,0.9993
17077,5,rs17642235,148644292,T,0.28950,0.289400,C,0.000004,9.984000e-01,1.0010
45990,18,rs4800148,20724328,G,0.28950,0.289400,A,0.000004,9.984000e-01,1.0010
30143,10,rs10829275,27836034,C,0.28950,0.289400,T,0.000004,9.984000e-01,1.0010
44706,17,rs16942,41244000,C,0.28950,0.289400,T,0.000004,9.984000e-01,1.0010
43934,17,rs2760743,2017079,A,0.28950,0.289400,C,0.000004,9.984000e-01,1.0010
43936,17,rs2984943,2030135,C,0.28950,0.289400,T,0.000004,9.984000e-01,1.0010
14526,4,rs7693453,177082069,C,0.14470,0.144700,G,0.000002,9.990000e-01,1.0000
38244,13,rs9519333,105080628,A,0.14470,0.144700,G,0.000002,9.990000e-01,1.0000
24371,8,rs13250464,1302323,T,0.14470,0.144700,C,0.000002,9.990000e-01,1.0000
778,1,rs4653087,35212534,T,0.14470,0.144700,C,0.000002,9.990000e-01,1.0000
34489,11,rs2575896,132488112,C,0.14470,0.144700,T,0.000002,9.990000e-01,1.0000
23712,7,rs281878,131822719,A,0.14470,0.144700,G,0.000002,9.990000e-01,1.0000
36203,12,rs76169231,102942969,C,0.14470,0.144700,T,0.000002,9.990000e-01,1.0000
34047,11,rs2846127,115828647,T,0.14470,0.144700,C,0.000002,9.990000e-01,1.0000
24056,7,rs77510079,149483237,A,0.14470,0.144700,G,0.000002,9.990000e-01,1.0000
36286,12,rs10861493,106121864,C,0.14470,0.144700,A,0.000002,9.990000e-01,1.0000
8311,3,rs2163907,5118220,A,0.14470,0.144700,G,0.000002,9.990000e-01,1.0000
25866,8,rs1900080,72179273,G,0.50000,0.500000,A,0.000000,1.000000e+00,1.0000

## Clumping example

In [205]:
clump = p.clump(gwas_file_name,clump_file_name="rr.assoc")

/data/jang/jang/tool/anaconda3/envs/ML/lib/python3.7/site-packages/ipykernel_launcher.py:90: FutureWarning: read_table is deprecated, use read_csv instead.

In [206]:
clump[['SNP']]

            SNP
0   rs117820043
1   rs144593206
2   rs188516474
3     rs6038805
4   rs139454297
5   rs192151622
6     rs9605004
7   rs118125172
8    rs75532401
9   rs150231433
10  rs188481973
11     rs754001
12  rs138423132
13   rs78791032
14      rs89062
15  rs150582084
16    rs7158191
17   rs17292295
18  rs115814039
19  rs189607229
20  rs148847534
21  rs144720593
22  rs143273589
23    rs7180788
24    rs3993374
25  rs117312059
26    rs9974185
27   rs10937705
28  rs146337832
29     rs214443
30   rs78811870